CREATE TABLE T_CONFIG (ID VARCHAR(50) NOT NULL, `NAME` VARCHAR(50) NOT NULL, S_VAL VARCHAR(1000), N_VAL DECIMAL(20, 6), CONFIG VARCHAR(100), PRIMARY KEY (ID));

CREATE TABLE T_PROCESSOR (IP VARCHAR(15) NOT NULL, PORT INT NOT NULL, IS_MASTER CHAR(1), IS_ACTIVE CHAR(1), IS_EMPTY CHAR(1) DEFAULT Y );

INSERT INTO pwsga.T_PROCESSOR (IP, PORT, IS_MASTER, IS_ACTIVE, IS_EMPTY) 
	VALUES ('172.17.0.1', 9010, 'Y', 'Y', 'Y');
INSERT INTO pwsga.T_PROCESSOR (IP, PORT, IS_MASTER, IS_ACTIVE, IS_EMPTY) 
	VALUES ('172.17.0.1', 9011, 'N', 'Y', 'Y');
INSERT INTO pwsga.T_PROCESSOR (IP, PORT, IS_MASTER, IS_ACTIVE, IS_EMPTY) 
	VALUES ('172.17.0.1', 9012, 'N', 'N', 'Y');
INSERT INTO pwsga.T_PROCESSOR (IP, PORT, IS_MASTER, IS_ACTIVE, IS_EMPTY) 
	VALUES ('172.17.0.1', 9013, 'N', 'N', 'Y');
INSERT INTO pwsga.T_PROCESSOR (IP, PORT, IS_MASTER, IS_ACTIVE, IS_EMPTY) 
	VALUES ('172.17.0.1', 9014, 'N', 'N', 'Y');
INSERT INTO pwsga.T_PROCESSOR (IP, PORT, IS_MASTER, IS_ACTIVE, IS_EMPTY) 
	VALUES ('172.17.0.1', 9015, 'N', 'N', 'Y');
INSERT INTO pwsga.T_PROCESSOR (IP, PORT, IS_MASTER, IS_ACTIVE, IS_EMPTY) 
	VALUES ('172.17.0.1', 9016, 'N', 'N', 'Y');
INSERT INTO pwsga.T_PROCESSOR (IP, PORT, IS_MASTER, IS_ACTIVE, IS_EMPTY) 
	VALUES ('172.17.0.1', 9017, 'N', 'N', 'Y');
INSERT INTO pwsga.T_PROCESSOR (IP, PORT, IS_MASTER, IS_ACTIVE, IS_EMPTY) 
	VALUES ('172.17.0.1', 9018, 'N', 'N', 'Y');

CREATE TABLE T_TRANSACTION (CONFIG_ID VARCHAR(50), ROUND_NO INT, `BEGIN` TIMESTAMP DEFAULT CURRENT_TIMESTAMP , `FOUND` TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE `T_WS_ENTRY` (
  `WS_ID` char(5) NOT NULL,
  `URL` varchar(1000) DEFAULT NULL,
  `COMPOSE` int(11) DEFAULT NULL,
  PRIMARY KEY (`WS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `T_WS_PARAM` (
  `PARAM_ID` varchar(25) NOT NULL,
  `PARAM_NAME` varchar(50) NOT NULL,
  `WS_ID` char(5) NOT NULL,
  `PARAM_TYPE` int(11) DEFAULT NULL,
  `SEQ` int(11) DEFAULT NULL,
  PRIMARY KEY (`PARAM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `T_WS_RESPS` (
  `RESPS_ID` varchar(25) NOT NULL,
  `RESPS_NAME` varchar(50) NOT NULL,
  `WS_ID` char(5) NOT NULL,
  `RESPS_TYPE` int(11) DEFAULT NULL,
  `SEQ` int(11) DEFAULT NULL,
  PRIMARY KEY (`RESPS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
